const { MongoClient } = require("mongodb");

// MongoDB connection details
const uri = "mongodb+srv://rippfball56:HenRocLiaYaBa@ryan-griego.x7xox5g.mongodb.net/?retryWrites=true&w=majority";
const DATABASE_NAME = "test"; // Replace with your database name
const COLLECTION_NAME = "jobs"; // Collection name is `jobs`

// All 15 documents
const documents = [
  {
    "jobPosterEmail": ["ryangriego@gmail.com"],
    "status": "Pending",
    "companyUrl": "https://www.examplecompany1.com",
    "companyName": "Example Company 1",
    "jobTitle": "Front-End Engineer",
    "jobLocation": "Remote",
    "postedAt": "2024-02-01T09:00:00.000Z",
    "appliesClosedAt": "2024-03-01T09:00:00.000Z",
    "jobDescription": "Work on front-end features using React and TailwindCSS.",
    "jobId": 1001,
    "workplaceType": "Remote",
    "companyLogoUrl": "https://www.examplecompany1.com/logo.png",
    "applyUrl": "https://www.examplecompany1.com/careers/apply",
    "experienceLevel": "Entry level",
    "applicantsCount": 0,
    "viewsCount": 10,
    "companyStaffCount": 50,
    "companyDescription": "A small startup focused on web applications.",
    "jobIndustries": "Internet",
    "jobFunctions": "Engineering",
    "remoteAllowed": "TRUE",
    "jobState": "OPEN",
    "jobType": "test",
    "timestamp": "2024-02-01T10:00:00.000Z",
    "query": "https://www.examplecompany1.com/jobs/1001",
    "error": "",
    "jobPosterProfileUrl": "",
    "jobPosterName": "Hiring Manager 1",
    "companyOfficialUrl": "https://www.examplecompany1.com",
    "source": "TestSource",
    "qrCodeUrl": "",
    "sentFollowUp1": false
  },
  {
    "jobPosterEmail": ["ryangriego@gmail.com"],
    "status": "Pending",
    "companyUrl": "https://www.examplecompany2.com",
    "companyName": "Example Company 2",
    "jobTitle": "Backend Developer",
    "jobLocation": "New York, NY",
    "postedAt": "2024-02-02T09:00:00.000Z",
    "appliesClosedAt": "2024-03-02T09:00:00.000Z",
    "jobDescription": "Focus on backend services with Node.js and MongoDB.",
    "jobId": 1002,
    "workplaceType": "On-site",
    "companyLogoUrl": "https://www.examplecompany2.com/logo.png",
    "applyUrl": "https://www.examplecompany2.com/careers/apply",
    "experienceLevel": "Mid level",
    "applicantsCount": 2,
    "viewsCount": 20,
    "companyStaffCount": 200,
    "companyDescription": "A well-established tech firm.",
    "jobIndustries": "Information Technology",
    "jobFunctions": "Engineering",
    "remoteAllowed": "FALSE",
    "jobState": "OPEN",
    "jobType": "test",
    "timestamp": "2024-02-02T10:00:00.000Z",
    "query": "https://www.examplecompany2.com/jobs/1002",
    "error": "",
    "jobPosterProfileUrl": "",
    "jobPosterName": "HR Team Member",
    "companyOfficialUrl": "https://www.examplecompany2.com",
    "source": "TestSource",
    "qrCodeUrl": "",
    "sentFollowUp1": false
  },
  {
    "jobPosterEmail": ["ryangriego@gmail.com"],
    "status": "Pending",
    "companyUrl": "https://www.examplecompany3.com",
    "companyName": "Example Company 3",
    "jobTitle": "UX Designer",
    "jobLocation": "San Francisco, CA",
    "postedAt": "2024-02-03T09:00:00.000Z",
    "appliesClosedAt": "2024-03-03T09:00:00.000Z",
    "jobDescription": "Design user-friendly interfaces for mobile and web.",
    "jobId": 1003,
    "workplaceType": "Hybrid",
    "companyLogoUrl": "https://www.examplecompany3.com/logo.png",
    "applyUrl": "https://www.examplecompany3.com/careers/apply",
    "experienceLevel": "Mid level",
    "applicantsCount": 5,
    "viewsCount": 15,
    "companyStaffCount": 120,
    "companyDescription": "A design-focused startup.",
    "jobIndustries": "Design",
    "jobFunctions": "Design",
    "remoteAllowed": "TRUE",
    "jobState": "OPEN",
    "jobType": "test",
    "timestamp": "2024-02-03T10:00:00.000Z",
    "query": "https://www.examplecompany3.com/jobs/1003",
    "error": "",
    "jobPosterProfileUrl": "",
    "jobPosterName": "Design Lead",
    "companyOfficialUrl": "https://www.examplecompany3.com",
    "source": "TestSource",
    "qrCodeUrl": "",
    "sentFollowUp1": false
  },
  {
    "jobPosterEmail": ["ryangriego@gmail.com"],
    "status": "Pending",
    "companyUrl": "https://www.examplecompany4.com",
    "companyName": "Example Company 4",
    "jobTitle": "DevOps Engineer",
    "jobLocation": "Austin, TX",
    "postedAt": "2024-02-04T09:00:00.000Z",
    "appliesClosedAt": "2024-03-04T09:00:00.000Z",
    "jobDescription": "Improve CI/CD pipelines and manage AWS infrastructure.",
    "jobId": 1004,
    "workplaceType": "Remote",
    "companyLogoUrl": "https://www.examplecompany4.com/logo.png",
    "applyUrl": "https://www.examplecompany4.com/careers/apply",
    "experienceLevel": "Senior level",
    "applicantsCount": 0,
    "viewsCount": 5,
    "companyStaffCount": 75,
    "companyDescription": "A cloud services optimization startup.",
    "jobIndustries": "Cloud Computing",
    "jobFunctions": "Engineering",
    "remoteAllowed": "TRUE",
    "jobState": "OPEN",
    "jobType": "test",
    "timestamp": "2024-02-04T10:00:00.000Z",
    "query": "https://www.examplecompany4.com/jobs/1004",
    "error": "",
    "jobPosterProfileUrl": "",
    "jobPosterName": "Tech Recruiter",
    "companyOfficialUrl": "https://www.examplecompany4.com",
    "source": "TestSource",
    "qrCodeUrl": "",
    "sentFollowUp1": false
  },
  {
    "jobPosterEmail": ["ryangriego@gmail.com"],
    "status": "Pending",
    "companyUrl": "https://www.examplecompany5.com",
    "companyName": "Example Company 5",
    "jobTitle": "Data Scientist",
    "jobLocation": "Boston, MA",
    "postedAt": "2024-02-05T09:00:00.000Z",
    "appliesClosedAt": "2024-03-05T09:00:00.000Z",
    "jobDescription": "Analyze data sets to inform product decisions.",
    "jobId": 1005,
    "workplaceType": "On-site",
    "companyLogoUrl": "https://www.examplecompany5.com/logo.png",
    "applyUrl": "https://www.examplecompany5.com/careers/apply",
    "experienceLevel": "Mid level",
    "applicantsCount": 3,
    "viewsCount": 25,
    "companyStaffCount": 300,
    "companyDescription": "A data-driven marketing firm.",
    "jobIndustries": "Marketing and Advertising",
    "jobFunctions": "Data",
    "remoteAllowed": "FALSE",
    "jobState": "OPEN",
    "jobType": "test",
    "timestamp": "2024-02-05T10:00:00.000Z",
    "query": "https://www.examplecompany5.com/jobs/1005",
    "error": "",
    "jobPosterProfileUrl": "",
    "jobPosterName": "Lead Recruiter",
    "companyOfficialUrl": "https://www.examplecompany5.com",
    "source": "TestSource",
    "qrCodeUrl": "",
    "sentFollowUp1": false
  },
  {
    "jobPosterEmail": ["ryangriego@gmail.com"],
    "status": "Pending",
    "companyUrl": "https://www.examplecompany6.com",
    "companyName": "Example Company 6",
    "jobTitle": "Mobile Developer",
    "jobLocation": "Chicago, IL",
    "postedAt": "2024-02-06T09:00:00.000Z",
    "appliesClosedAt": "2024-03-06T09:00:00.000Z",
    "jobDescription": "Build React Native apps for iOS and Android.",
    "jobId": 1006,
    "workplaceType": "Hybrid",
    "companyLogoUrl": "https://www.examplecompany6.com/logo.png",
    "applyUrl": "https://www.examplecompany6.com/careers/apply",
    "experienceLevel": "Entry level",
    "applicantsCount": 1,
    "viewsCount": 8,
    "companyStaffCount": 25,
    "companyDescription": "A small mobile consulting agency.",
    "jobIndustries": "Mobile Apps",
    "jobFunctions": "Engineering",
    "remoteAllowed": "TRUE",
    "jobState": "OPEN",
    "jobType": "test",
    "timestamp": "2024-02-06T10:00:00.000Z",
    "query": "https://www.examplecompany6.com/jobs/1006",
    "error": "",
    "jobPosterProfileUrl": "",
    "jobPosterName": "Recruiting Coordinator",
    "companyOfficialUrl": "https://www.examplecompany6.com",
    "source": "TestSource",
    "qrCodeUrl": "",
    "sentFollowUp1": false
  },
  {
    "jobPosterEmail": ["ryangriego@gmail.com"],
    "status": "Pending",
    "companyUrl": "https://www.examplecompany7.com",
    "companyName": "Example Company 7",
    "jobTitle": "QA Engineer",
    "jobLocation": "Los Angeles, CA",
    "postedAt": "2024-02-07T09:00:00.000Z",
    "appliesClosedAt": "2024-03-07T09:00:00.000Z",
    "jobDescription": "Test and ensure quality of web applications.",
    "jobId": 1007,
    "workplaceType": "Remote",
    "companyLogoUrl": "https://www.examplecompany7.com/logo.png",
    "applyUrl": "https://www.examplecompany7.com/careers/apply",
    "experienceLevel": "Mid level",
    "applicantsCount": 0,
    "viewsCount": 4,
    "companyStaffCount": 100,
    "companyDescription": "A QA-focused agency.",
    "jobIndustries": "Software",
    "jobFunctions": "Quality Assurance",
    "remoteAllowed": "TRUE",
    "jobState": "OPEN",
    "jobType": "test",
    "timestamp": "2024-02-07T10:00:00.000Z",
    "query": "https://www.examplecompany7.com/jobs/1007",
    "error": "",
    "jobPosterProfileUrl": "",
    "jobPosterName": "QA Lead",
    "companyOfficialUrl": "https://www.examplecompany7.com",
    "source": "TestSource",
    "qrCodeUrl": "",
    "sentFollowUp1": false
  },
  {
    "jobPosterEmail": ["ryangriego@gmail.com"],
    "status": "Pending",
    "companyUrl": "https://www.examplecompany8.com",
    "companyName": "Example Company 8",
    "jobTitle": "Product Manager",
    "jobLocation": "Seattle, WA",
    "postedAt": "2024-02-08T09:00:00.000Z",
    "appliesClosedAt": "2024-03-08T09:00:00.000Z",
    "jobDescription": "Define product roadmap and feature priorities.",
    "jobId": 1008,
    "workplaceType": "Hybrid",
    "companyLogoUrl": "https://www.examplecompany8.com/logo.png",
    "applyUrl": "https://www.examplecompany8.com/careers/apply",
    "experienceLevel": "Senior level",
    "applicantsCount": 2,
    "viewsCount": 18,
    "companyStaffCount": 500,
    "companyDescription": "A large tech company.",
    "jobIndustries": "Technology",
    "jobFunctions": "Product Management",
    "remoteAllowed": "TRUE",
    "jobState": "OPEN",
    "jobType": "test",
    "timestamp": "2024-02-08T10:00:00.000Z",
    "query": "https://www.examplecompany8.com/jobs/1008",
    "error": "",
    "jobPosterProfileUrl": "",
    "jobPosterName": "Lead PM",
    "companyOfficialUrl": "https://www.examplecompany8.com",
    "source": "TestSource",
    "qrCodeUrl": "",
    "sentFollowUp1": false
  },
  {
    "jobPosterEmail": ["ryangriego@gmail.com"],
    "status": "Pending",
    "companyUrl": "https://www.examplecompany9.com",
    "companyName": "Example Company 9",
    "jobTitle": "Technical Writer",
    "jobLocation": "Portland, OR",
    "postedAt": "2024-02-09T09:00:00.000Z",
    "appliesClosedAt": "2024-03-09T09:00:00.000Z",
    "jobDescription": "Write and maintain technical documentation.",
    "jobId": 1009,
    "workplaceType": "Remote",
    "companyLogoUrl": "https://www.examplecompany9.com/logo.png",
    "applyUrl": "https://www.examplecompany9.com/careers/apply",
    "experienceLevel": "Mid level",
    "applicantsCount": 0,
    "viewsCount": 6,
    "companyStaffCount": 60,
    "companyDescription": "A tech documentation startup.",
    "jobIndustries": "Technical Writing",
    "jobFunctions": "Writing/Documentation",
    "remoteAllowed": "TRUE",
    "jobState": "OPEN",
    "jobType": "test",
    "timestamp": "2024-02-09T10:00:00.000Z",
    "query": "https://www.examplecompany9.com/jobs/1009",
    "error": "",
    "jobPosterProfileUrl": "",
    "jobPosterName": "Docs Manager",
    "companyOfficialUrl": "https://www.examplecompany9.com",
    "source": "TestSource",
    "qrCodeUrl": "",
    "sentFollowUp1": false
  },
  {
    "jobPosterEmail": ["ryangriego@gmail.com"],
    "status": "Pending",
    "companyUrl": "https://www.examplecompany10.com",
    "companyName": "Example Company 10",
    "jobTitle": "Sales Engineer",
    "jobLocation": "Miami, FL",
    "postedAt": "2024-02-10T09:00:00.000Z",
    "appliesClosedAt": "2024-03-10T09:00:00.000Z",
    "jobDescription": "Bridge sales and engineering teams to meet client needs.",
    "jobId": 1010,
    "workplaceType": "On-site",
    "companyLogoUrl": "https://www.examplecompany10.com/logo.png",
    "applyUrl": "https://www.examplecompany10.com/careers/apply",
    "experienceLevel": "Mid level",
    "applicantsCount": 1,
    "viewsCount": 7,
    "companyStaffCount": 200,
    "companyDescription": "A tech solutions provider.",
    "jobIndustries": "Sales",
    "jobFunctions": "Engineering/Sales",
    "remoteAllowed": "FALSE",
    "jobState": "OPEN",
    "jobType": "test",
    "timestamp": "2024-02-10T10:00:00.000Z",
    "query": "https://www.examplecompany10.com/jobs/1010",
    "error": "",
    "jobPosterProfileUrl": "",
    "jobPosterName": "Sales Lead",
    "companyOfficialUrl": "https://www.examplecompany10.com",
    "source": "TestSource",
    "qrCodeUrl": "",
    "sentFollowUp1": false
  },
  {
    "jobPosterEmail": ["ryangriego@gmail.com"],
    "status": "Pending",
    "companyUrl": "https://www.examplecompany11.com",
    "companyName": "Example Company 11",
    "jobTitle": "Security Analyst",
    "jobLocation": "Denver, CO",
    "postedAt": "2024-02-11T09:00:00.000Z",
    "appliesClosedAt": "2024-03-11T09:00:00.000Z",
    "jobDescription": "Monitor and secure network systems.",
    "jobId": 1011,
    "workplaceType": "Hybrid",
    "companyLogoUrl": "https://www.examplecompany11.com/logo.png",
    "applyUrl": "https://www.examplecompany11.com/careers/apply",
    "experienceLevel": "Senior level",
    "applicantsCount": 4,
    "viewsCount": 12,
    "companyStaffCount": 80,
    "companyDescription": "Cybersecurity startup.",
    "jobIndustries": "Cybersecurity",
    "jobFunctions": "Security",
    "remoteAllowed": "TRUE",
    "jobState": "OPEN",
    "jobType": "test",
    "timestamp": "2024-02-11T10:00:00.000Z",
    "query": "https://www.examplecompany11.com/jobs/1011",
    "error": "",
    "jobPosterProfileUrl": "",
    "jobPosterName": "Security Lead",
    "companyOfficialUrl": "https://www.examplecompany11.com",
    "source": "TestSource",
    "qrCodeUrl": "",
    "sentFollowUp1": false
  },
  {
    "jobPosterEmail": ["ryangriego@gmail.com"],
    "status": "Pending",
    "companyUrl": "https://www.examplecompany12.com",
    "companyName": "Example Company 12",
    "jobTitle": "UI Developer",
    "jobLocation": "San Diego, CA",
    "postedAt": "2024-02-12T09:00:00.000Z",
    "appliesClosedAt": "2024-03-12T09:00:00.000Z",
    "jobDescription": "Implement responsive UI components.",
    "jobId": 1012,
    "workplaceType": "On-site",
    "companyLogoUrl": "https://www.examplecompany12.com/logo.png",
    "applyUrl": "https://www.examplecompany12.com/careers/apply",
    "experienceLevel": "Entry level",
    "applicantsCount": 0,
    "viewsCount": 3,
    "companyStaffCount": 30,
    "companyDescription": "A small UI/UX studio.",
    "jobIndustries": "Design/Tech",
    "jobFunctions": "Engineering",
    "remoteAllowed": "FALSE",
    "jobState": "OPEN",
    "jobType": "test",
    "timestamp": "2024-02-12T10:00:00.000Z",
    "query": "https://www.examplecompany12.com/jobs/1012",
    "error": "",
    "jobPosterProfileUrl": "",
    "jobPosterName": "HR Coordinator",
    "companyOfficialUrl": "https://www.examplecompany12.com",
    "source": "TestSource",
    "qrCodeUrl": "",
    "sentFollowUp1": false
  },
  {
    "jobPosterEmail": ["ryangriego@gmail.com"],
    "status": "Pending",
    "companyUrl": "https://www.examplecompany13.com",
    "companyName": "Example Company 13",
    "jobTitle": "Marketing Specialist",
    "jobLocation": "Atlanta, GA",
    "postedAt": "2024-02-13T09:00:00.000Z",
    "appliesClosedAt": "2024-03-13T09:00:00.000Z",
    "jobDescription": "Plan and execute marketing campaigns.",
    "jobId": 1013,
    "workplaceType": "Remote",
    "companyLogoUrl": "https://www.examplecompany13.com/logo.png",
    "applyUrl": "https://www.examplecompany13.com/careers/apply",
    "experienceLevel": "Mid level",
    "applicantsCount": 1,
    "viewsCount": 9,
    "companyStaffCount": 150,
    "companyDescription": "A marketing consultancy.",
    "jobIndustries": "Marketing",
    "jobFunctions": "Marketing",
    "remoteAllowed": "TRUE",
    "jobState": "OPEN",
    "jobType": "test",
    "timestamp": "2024-02-13T10:00:00.000Z",
    "query": "https://www.examplecompany13.com/jobs/1013",
    "error": "",
    "jobPosterProfileUrl": "",
    "jobPosterName": "Marketing Lead",
    "companyOfficialUrl": "https://www.examplecompany13.com",
    "source": "TestSource",
    "qrCodeUrl": "",
    "sentFollowUp1": false
  },
  {
    "jobPosterEmail": ["ryangriego@gmail.com"],
    "status": "Pending",
    "companyUrl": "https://www.examplecompany14.com",
    "companyName": "Example Company 14",
    "jobTitle": "Database Administrator",
    "jobLocation": "Remote",
    "postedAt": "2024-02-14T09:00:00.000Z",
    "appliesClosedAt": "2024-03-14T09:00:00.000Z",
    "jobDescription": "Manage and optimize SQL databases.",
    "jobId": 1014,
    "workplaceType": "Remote",
    "companyLogoUrl": "https://www.examplecompany14.com/logo.png",
    "applyUrl": "https://www.examplecompany14.com/careers/apply",
    "experienceLevel": "Senior level",
    "applicantsCount": 2,
    "viewsCount": 11,
    "companyStaffCount": 90,
    "companyDescription": "A database solutions provider.",
    "jobIndustries": "IT Services",
    "jobFunctions": "Database Management",
    "remoteAllowed": "TRUE",
    "jobState": "OPEN",
    "jobType": "test",
    "timestamp": "2024-02-14T10:00:00.000Z",
    "query": "https://www.examplecompany14.com/jobs/1014",
    "error": "",
    "jobPosterProfileUrl": "",
    "jobPosterName": "DB Lead",
    "companyOfficialUrl": "https://www.examplecompany14.com",
    "source": "TestSource",
    "qrCodeUrl": "",
    "sentFollowUp1": false
  },
  {
    "jobPosterEmail": ["ryangriego@gmail.com"],
    "status": "Pending",
    "companyUrl": "https://www.examplecompany15.com",
    "companyName": "Example Company 15",
    "jobTitle": "SEO Specialist",
    "jobLocation": "Philadelphia, PA",
    "postedAt": "2024-02-15T09:00:00.000Z",
    "appliesClosedAt": "2024-03-15T09:00:00.000Z",
    "jobDescription": "Optimize website ranking and search engine visibility.",
    "jobId": 1015,
    "workplaceType": "Hybrid",
    "companyLogoUrl": "https://www.examplecompany15.com/logo.png",
    "applyUrl": "https://www.examplecompany15.com/careers/apply",
    "experienceLevel": "Mid level",
    "applicantsCount": 1,
    "viewsCount": 4,
    "companyStaffCount": 40,
    "companyDescription": "A digital marketing firm.",
    "jobIndustries": "Marketing",
    "jobFunctions": "SEO",
    "remoteAllowed": "TRUE",
    "jobState": "OPEN",
    "jobType": "test",
    "timestamp": "2024-02-15T10:00:00.000Z",
    "query": "https://www.examplecompany15.com/jobs/1015",
    "error": "",
    "jobPosterProfileUrl": "",
    "jobPosterName": "SEO Lead",
    "companyOfficialUrl": "https://www.examplecompany15.com",
    "source": "TestSource",
    "qrCodeUrl": "",
    "sentFollowUp1": false
  }
];

(async () => {
  const client = new MongoClient(uri);

  try {
    await client.connect();
    console.log("Connected to MongoDB");

    // Specify database and collection
    const db = client.db(DATABASE_NAME);
    const collection = db.collection(COLLECTION_NAME);

    // Insert all documents into the collection
    const result = await collection.insertMany(documents);
    console.log(`Inserted ${result.insertedCount} documents into the '${COLLECTION_NAME}' collection.`);
  } catch (error) {
    console.error("Error inserting documents:", error);
  } finally {
    await client.close();
    console.log("MongoDB connection closed.");
  }
})();
